version: "3"

# Holds ext. dependency services
services:
  syslog-ng:
    image : balabit/syslog-ng:latest
    hostname: syslog
    restart: always
    command: "--no-caps"

    cap_drop:
      - ALL

    cap_add:
      # Allows us to bind to port 601
      - NET_BIND_SERVICE

    volumes:
      # Map custom config in
      - ./conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./mount/syslog-ng:/var/log/syslog

    ports:
      - "601:601"
      - "514:514"