version: "3"

# Holds ext. dependency services
services:
  syslog-ng:
    image : balabit/syslog-ng:latest
    hostname: syslog
    command: "--no-caps --foreground"

    cap_drop:
      - ALL

    cap_add:
      # Allows us to bind to port 601
      - NET_BIND_SERVICE

    volumes:
      # Map custom config in
      - ./conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./mount/syslog-ng/log:/var/log

    ports:
      - "601:601"
      - "514:514"

  maria-db:
    image: mariadb:latest
    hostname : mariadb

    ports:
      - "3306:3306"

    volumes:
      - ./mount/maria-db:/var/lib/mysql

    # If a password is not present this will exit out
    environment:
      - MYSQL_ROOT_PASSWORD
      # For testing you could also use the followig line
      # - MYSQL_ROOT_PASSWORD=your_pass