version: "2"

services:
## External containers
  syslogng:
    image : balabit/syslog-ng:latest
    command: "--no-caps --foreground"
    cap_drop:
      - ALL
    volumes:
      - ./conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - ex_syslog_logs:/var/log
    networks:
      - aberfitness

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ex_mariadb_data:/var/lib/mysql
    env_file:
      - env/mariadb.env
    networks:
      - aberfitness

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ex_nginx_logs:/var/log/nginx/
      - shared_certificates:/certs/
    networks:
      - aberfitness


## AberFitness containers
  gatekeeper:
    image: sem56402018/gatekeeper:${DEPLOYMENT_TAG}
    volumes:
      - af_gatekeeper_certs:/certs
      - af_gatekeeper_keys:/keys
    env_file:
      - env/gatekeeper.env
    networks:
      - aberfitness
    depends_on:
      - "mariadb"

networks:
  aberfitness:

volumes:
  ex_syslog_logs:
  ex_mariadb_data:
  ex_nginx_logs:
  af_gatekeeper_certs:
  af_gatekeeper_keys:
  
