version: "2"

services:
## External containers
  syslogng:
    image : balabit/syslog-ng:latest
    command: "--no-caps --foreground"
    cap_drop:
      - ALL
    volumes:
      - ./conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro
      - syslog_logs:/var/log:rw
    networks:
      - aberfitness

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    env_file:
      - env/mariadb.env
    networks:
      - aberfitness

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx/:rw
      - shared_certs:/certs/:ro
    networks:
      - aberfitness
    depends_on:
      - gatekeeper
      - health-data-repository
      - health-dashboard
      - booking-facilities


## AberFitness containers
  gatekeeper:
    image: sem56402018/gatekeeper:${DEPLOYMENT_TAG}
    volumes:
      - shared_certs:/certs:ro
      - shared_keys:/keys:rw
    env_file:
      - env/gatekeeper.env
    networks:
      - aberfitness
    depends_on:
      - mariadb

  health-data-repository:
    image: sem56402018/health-data-repository:${DEPLOYMENT_TAG}
    volumes:
      - shared_certs:/certs:ro
    env_file:
      - env/health-data-repository.env
    networks:
      - aberfitness
    depends_on:
      - mariadb

  health-dashboard:
    image: sem56402018/health-dashboard:${DEPLOYMENT_TAG}
    volumes:
      - shared_certs:/certs:ro
    env_file:
      - env/health-dashboard.env
    networks:
      - aberfitness
    depends_on:
      - mariadb

  booking-facilities:
    image: sem56402018/booking-facilities:${DEPLOYMENT_TAG}
    volumes:
      - shared_certs:/certs:ro
    env_file:
      - env/booking-facilities.env
    networks:
      - aberfitness
    depends_on:
      - mariadb

networks:
  aberfitness:

volumes:
  shared_certs:
  shared_keys:
  syslog_logs:
  nginx_logs:
  mariadb_data:
  
